<a href="https://colab.research.google.com/github/arthurzaneti/pytorch-fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
# What is a Tensor?

# The way I get it is that Tensor is a n dimensional matrix.
# But I hope this gets clearer trought the course

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,7])


In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8], [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3], [3, 2, 1]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 2, 1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
TENSOR[0][1][1]

tensor(2)

In [ ]:
MY_TENSOR = torch.tensor([[[1, 2, 3, 4],
                           [1, 2, 3, 4],
                            [1, 2, 3, 4]],
                           [[1, 2, 3, 4],
                           [1, 2, 3, 4],
                            [1, 2, 3, 4]],
                           [[1, 2, 3, 4],
                           [1, 2, 3, 4],
                            [1, 2, 3, 4]]])
MY_TENSOR

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]])

In [ ]:
MY_TENSOR.ndim

3

In [ ]:
MY_TENSOR.shape

torch.Size([3, 3, 4])

  I feel like a Tensor is actually a bit more general than an N dimensional matrix.
 I say that because scalars are 0 dimensional tensors, vectors a 1 dimensional tensors
 and matrices are 2 dimensional tensors. So tensors are the most general structure to represent
 a group of numbers



 ### Random tensors

 Why would you use a random tensor? They are important because the way a neural network lears is starting with a random numbers (a random tensor with a specified size) and adjust them to fit outputs

In [ ]:
RTENSOR = torch.rand(3, 4, 2, 2, 2)
RTENSOR

tensor([[[[[0.2557, 0.2653],
           [0.1370, 0.7228]],

          [[0.0853, 0.7589],
           [0.7450, 0.1177]]],


         [[[0.3892, 0.4868],
           [0.9410, 0.0494]],

          [[0.6689, 0.1343],
           [0.3868, 0.3502]]],


         [[[0.7140, 0.9976],
           [0.2709, 0.2280]],

          [[0.5401, 0.3755],
           [0.8963, 0.8294]]],


         [[[0.5339, 0.2061],
           [0.8972, 0.6161]],

          [[0.4731, 0.3853],
           [0.4761, 0.2177]]]],



        [[[[0.9169, 0.8649],
           [0.7184, 0.6263]],

          [[0.0918, 0.0678],
           [0.2103, 0.7234]]],


         [[[0.4407, 0.2022],
           [0.5649, 0.6841]],

          [[0.4433, 0.6593],
           [0.0087, 0.7886]]],


         [[[0.8026, 0.5070],
           [0.6019, 0.3782]],

          [[0.3600, 0.5867],
           [0.9955, 0.1604]]],


         [[[0.8903, 0.5157],
           [0.5998, 0.1802]],

          [[0.4097, 0.5285],
           [0.3234, 0.6991]]]],



        [[[[0.8989, 

In [ ]:
RTENSOR.ndim

5

In [ ]:
RTENSOR.shape

torch.Size([3, 4, 2, 2, 2])

In [ ]:
RIMG_TENSOR = torch.rand(3, 224, 224)
RIMG_TENSOR.ndim, RIMG_TENSOR.shape

(3, torch.Size([3, 224, 224]))

In [ ]:
MY_RTENSOR = torch.rand(2, 2, 2, 2, 2, 2, 2, 2)

## Tensors of Zeros and ones

In [ ]:
ZEROS = torch.zeros(size = (3,4))
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.rand(size = (3,4)) * ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ONES = torch.ones(3, 4, 1)
ONES

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [ ]:
ONES.dtype

torch.float32

In [ ]:
# torch.arange
torch.arange(start = 0, end = 10, step = 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
# tensors like
ten_zeros = torch.zeros_like(input = ONES)
ten_zeros

tensor([[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]])

In [ ]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
real = torch.rand(2, 2)
imag = torch.rand(2, 2)
z = torch.complex(real, imag)
print(z)
z.dtype

tensor([[0.9853+0.9734j, 0.3117+0.9753j],
        [0.1913+0.6351j, 0.6752+0.5358j]])


torch.complex64