<a href="https://colab.research.google.com/github/arthurzaneti/pytorch-fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
# What is a Tensor?

# The way I get it is that Tensor is a n dimensional matrix.
# But I hope this gets clearer trought the course

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,7])


In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8], [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3], [3, 2, 1]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 2, 1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
TENSOR[0][1][1]

tensor(2)

In [ ]:
MY_TENSOR = torch.tensor([[[1, 2, 3, 4],
                           [1, 2, 3, 4],
                            [1, 2, 3, 4]],
                           [[1, 2, 3, 4],
                           [1, 2, 3, 4],
                            [1, 2, 3, 4]],
                           [[1, 2, 3, 4],
                           [1, 2, 3, 4],
                            [1, 2, 3, 4]]])
MY_TENSOR

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]])

In [ ]:
MY_TENSOR.ndim

3

In [ ]:
MY_TENSOR.shape

torch.Size([3, 3, 4])

  I feel like a Tensor is actually a bit more general than an N dimensional matrix.
 I say that because scalars are 0 dimensional tensors, vectors a 1 dimensional tensors
 and matrices are 2 dimensional tensors. So tensors are the most general structure to represent
 a group of numbers



 ### Random tensors

 Why would you use a random tensor? They are important because the way a neural network lears is starting with a random numbers (a random tensor with a specified size) and adjust them to fit outputs

In [ ]:
RTENSOR = torch.rand(3, 4, 2, 2, 2)
RTENSOR

tensor([[[[[0.6586, 0.9743],
           [0.2283, 0.6690]],

          [[0.3130, 0.7379],
           [0.9326, 0.9801]]],


         [[[0.0409, 0.6333],
           [0.2543, 0.4016]],

          [[0.6149, 0.6250],
           [0.4819, 0.1952]]],


         [[[0.9130, 0.2092],
           [0.9562, 0.0792]],

          [[0.4563, 0.2149],
           [0.8302, 0.5786]]],


         [[[0.2401, 0.8449],
           [0.6568, 0.7962]],

          [[0.6144, 0.6262],
           [0.1364, 0.8977]]]],



        [[[[0.9405, 0.8254],
           [0.9088, 0.2015]],

          [[0.0884, 0.3367],
           [0.6020, 0.9586]]],


         [[[0.1809, 0.2165],
           [0.4995, 0.7640]],

          [[0.3059, 0.8682],
           [0.7008, 0.8229]]],


         [[[0.3911, 0.9089],
           [0.3667, 0.6137]],

          [[0.0312, 0.3924],
           [0.9955, 0.5003]]],


         [[[0.8066, 0.6748],
           [0.3595, 0.1062]],

          [[0.8415, 0.0770],
           [0.9395, 0.7012]]]],



        [[[[0.6616, 

In [ ]:
RTENSOR.ndim

5

In [ ]:
RTENSOR.shape

torch.Size([3, 4, 2, 2, 2])

In [ ]:
RIMG_TENSOR = torch.rand(3, 224, 224)
RIMG_TENSOR.ndim, RIMG_TENSOR.shape

(3, torch.Size([3, 224, 224]))

In [ ]:
MY_RTENSOR = torch.rand(2, 2, 2, 2, 2, 2, 2, 2)

## Tensors of Zeros and ones

In [ ]:
ZEROS = torch.zeros(size = (3,4))
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.rand(size = (3,4)) * ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ONES = torch.ones(3, 4, 1)
ONES

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [ ]:
ONES.dtype

torch.float32

In [ ]:
# torch.arange
torch.arange(start = 0, end = 10, step = 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
# tensors like
ten_zeros = torch.zeros_like(input = ONES)
ten_zeros

tensor([[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]])

In [ ]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
real = torch.rand(2, 2)
imag = torch.rand(2, 2)
z = torch.complex(real, imag)
print(z)
z.dtype

tensor([[0.9558+0.8393j, 0.8951+0.2121j],
        [0.9698+0.6991j, 0.1364+0.3228j]])


torch.complex64

#Tensor Datatypes

**Note:** Tensor datatypes are one of the three main sources of errors in Deep learning

1. Tensor not right dtype
2. Tensor not having the right shape
3. Tensors not on the right device (????)

In [ ]:
float_32_TENSOR = torch.tensor([3], dtype = torch.float64,
                               device = None, #cuda, gpu, cpu
                               requires_grad = False)

In [ ]:
float_16_TENSOR = float_32_TENSOR.type(torch.float16)
float_16_TENSOR.dtype

torch.float16

In [ ]:
print(float_16_TENSOR)
print(float_32_TENSOR)
float_16_TENSOR * float_32_TENSOR

tensor([3.], dtype=torch.float16)
tensor([3.], dtype=torch.float64)


tensor([9.], dtype=torch.float64)

In [ ]:
int_64_TENSOR = torch.tensor([3, 6, 9])
int_64_TENSOR.dtype

torch.int64

In [ ]:
float_32_TENSOR * int_32_TENSOR

tensor([ 9., 18., 27.], dtype=torch.float64)

###Formalizing
Getting tensor attributes


In [ ]:
my_tensor = torch.rand(3, 4, 2).type(torch.float64).to(device = "cpu")
print(my_tensor.dtype)
print(my_tensor.shape)
print(my_tensor.device)

torch.float64
torch.Size([3, 4, 2])
cpu


# Manipulating tensors

Standard Tensor operations include:
1.Addition
2.Substraction
3.Multiplicaton (element-wise)
4.Division
5.Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([1, 2, 3])
tensor + tensor2

tensor([2, 4, 6])

In [ ]:
tensor + 2

tensor([3, 4, 5])

In [ ]:
tensor * tensor2

tensor([1, 4, 9])

In [ ]:
tensor / tensor2

tensor([1., 1., 1.])

In [ ]:
torch.add(tensor, tensor2)

tensor([2, 4, 6])

###Matrix multiplication

It is a bit more complicated than just element wise right but lets take a look (can be also called dot product)

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.03 ms, sys: 974 µs, total: 2 ms
Wall time: 2.04 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 105 µs, sys: 7 µs, total: 112 µs
Wall time: 117 µs


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 0 ns, sys: 836 µs, total: 836 µs
Wall time: 688 µs


tensor(14)

Note that torch's implementation is infinitely faster. Also note that the matrice multiplication shouldn't have worked, but it does because of the way torch.matmul handles multiplication between two vectors, it just multiplies element wise and than adds the results

Normally, matrice multiplication needs to satisfy the basic rules for matrice multiplication though (inner dimensions must match)

In [ ]:
# Will not work
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: ignored

In [ ]:
# Works because it transfors the second torch into a shape of 3x1
torch.matmul(torch.rand(2, 3), torch.rand(3)).shape

torch.Size([2])

In [ ]:
tensor_b = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_a = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

In [ ]:
# Example of not working
torch.mm(tensor_a, tensor_b)

RuntimeError: ignored

In [ ]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix this we could use **transpose** which effectively rotates pi/2 the matrice, or swaps dimensions

In [ ]:
tensor_b

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_b.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
tensor_b.T.shape, tensor_b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
tensor_c = torch.tensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]]])

In [ ]:
tensor_c.shape

torch.Size([2, 2, 2])

In [ ]:
tensor_c

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
tensor_c.T

<ipython-input-86-99b1377dfaf2>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3571.)
  tensor_c.T


tensor([[[1, 5],
         [3, 7]],

        [[2, 6],
         [4, 8]]])

Transpose works for higher dimensions but its not recommended

In [ ]:
# Torch compressing the 3d 2x2x2 into a 2d 2x4 matrice to make the multiplication
torch.matmul(tensor_c, tensor_a.T)

tensor([[[ 27,  30,  33],
         [ 61,  68,  75]],

        [[ 95, 106, 117],
         [129, 144, 159]]])

In [ ]:
torch.matmul(tensor_a, tensor_c)

tensor([[[ 37,  54],
         [ 41,  60],
         [ 45,  66]],

        [[105, 122],
         [117, 136],
         [129, 150]]])

#Finding min, max, mean, sum and etc

In [ ]:
x = torch.arange(0, 100, 10)

In [ ]:
x.min()

tensor(0)

In [ ]:
x.type(torch.float32).max()

tensor(90.)

In [ ]:
# torch.mean() doesn't work with longs (integers)
x.type(torch.float64).mean()

tensor(45., dtype=torch.float64)

In [ ]:
tensor_d = torch.rand(4, 4, 4, 4)

In [ ]:
tensor_d

tensor([[[[0.8312, 0.0037, 0.4350, 0.2271],
          [0.3414, 0.3101, 0.8504, 0.4678],
          [0.8801, 0.3191, 0.4485, 0.4791],
          [0.2611, 0.2553, 0.4474, 0.8219]],

         [[0.3667, 0.6216, 0.3528, 0.8815],
          [0.4752, 0.6316, 0.5496, 0.5345],
          [0.2651, 0.6687, 0.3628, 0.1719],
          [0.3527, 0.5088, 0.5949, 0.0433]],

         [[0.1756, 0.2218, 0.4432, 0.4829],
          [0.6427, 0.4935, 0.4789, 0.7464],
          [0.8975, 0.1799, 0.7434, 0.2751],
          [0.0736, 0.6898, 0.4388, 0.1036]],

         [[0.3213, 0.6143, 0.3062, 0.6498],
          [0.0670, 0.3457, 0.7616, 0.3412],
          [0.9836, 0.2644, 0.2500, 0.7914],
          [0.8757, 0.2538, 0.0961, 0.3221]]],


        [[[0.2857, 0.7864, 0.1589, 0.5270],
          [0.5886, 0.6124, 0.2125, 0.3771],
          [0.0719, 0.0019, 0.8515, 0.0332],
          [0.0839, 0.8322, 0.8451, 0.7960]],

         [[0.4776, 0.6429, 0.5240, 0.0147],
          [0.9475, 0.6325, 0.9949, 0.6053],
          [0.3677, 0

In [ ]:
torch.argmin(tensor_d, dim = 3)

tensor([[[1, 1, 1, 1],
         [2, 0, 3, 3],
         [0, 2, 1, 0],
         [2, 0, 2, 2]],

        [[2, 2, 1, 0],
         [3, 3, 3, 3],
         [3, 1, 0, 0],
         [3, 3, 2, 3]],

        [[3, 2, 2, 0],
         [2, 3, 2, 3],
         [0, 0, 1, 3],
         [2, 0, 1, 1]],

        [[2, 3, 1, 0],
         [0, 2, 2, 0],
         [3, 0, 2, 3],
         [3, 2, 0, 3]]])

## Reshaping tensors, stacking, squeezing and unsqueezing.

* Reshaping - reshapes an input tensor (simple af)
* View - Return a view of the input tensor but keep the same memory as the original

* Stack - Combine multiple tensors on top of each other

* Squeeze - removes all '1' dimensions from a tensor

* Unsqueeze - add a '1' dimension to a tensor

* Permute - Return a view of the input with dimensions swapped (in a specified way)


In [1]:
# Importing torch to not need to run all code above
import torch

In [2]:
t = torch.arange(1., 10.)
t, t.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
t_reshaped = t.reshape(3, 3)

In [12]:
z = t.view(1, 9)
z, z.shape

#But z actually shares memory with t

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
z[0, 0] = 5.
t, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [20]:
tz = torch.vstack([t, z])
tz[0, 0] = 2
tz

tensor([[2., 2., 3., 4., 5., 6., 7., 8., 9.],
        [2., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [39]:
t1 = torch.rand(3, 3)
t2 = torch.rand(3, 3)

t1, t2

(tensor([[0.5732, 0.2201, 0.4357],
         [0.7347, 0.5292, 0.1795],
         [0.4615, 0.0870, 0.2632]]),
 tensor([[0.6998, 0.5333, 0.0477],
         [0.9624, 0.8674, 0.5202],
         [0.9935, 0.8502, 0.5360]]))

In [54]:
t1_unsqueezed = torch.unsqueeze(t1, dim = 2)
t1_unsqueezed

tensor([[[0.5732],
         [0.2201],
         [0.4357]],

        [[0.7347],
         [0.5292],
         [0.1795]],

        [[0.4615],
         [0.0870],
         [0.2632]]])

In [55]:
t1_squeezed = torch.squeeze(t1)
t1_squeezed

tensor([[0.5732, 0.2201, 0.4357],
        [0.7347, 0.5292, 0.1795],
        [0.4615, 0.0870, 0.2632]])

In [57]:
t_reshaped.shape

torch.Size([3, 3])

In [61]:
# Resume
t3 = torch.rand(3, 3)
print(f"Normal tensor {t3}")
print("________________________________")
print(f"unsqueezed in dim 0 {torch.unsqueeze(t3, dim = 0)}")
print("________________________________")
print(f"unsqueezed in dim 1 {torch.unsqueeze(t3, dim = 1)}")
print("________________________________")
print(f"unsqueezed in dim 2 {torch.unsqueeze(t3, dim = 2)}")
print("________________________________")
print(f"squeezed back {torch.squeeze(t3)}")

Normal tensor tensor([[0.2278, 0.8095, 0.5995],
        [0.0878, 0.0887, 0.1695],
        [0.5426, 0.9110, 0.4409]])
________________________________
unsqueezed in dim 0 tensor([[[0.2278, 0.8095, 0.5995],
         [0.0878, 0.0887, 0.1695],
         [0.5426, 0.9110, 0.4409]]])
________________________________
unsqueezed in dim 1 tensor([[[0.2278, 0.8095, 0.5995]],

        [[0.0878, 0.0887, 0.1695]],

        [[0.5426, 0.9110, 0.4409]]])
________________________________
unsqueezed in dim 2 tensor([[[0.2278],
         [0.8095],
         [0.5995]],

        [[0.0878],
         [0.0887],
         [0.1695]],

        [[0.5426],
         [0.9110],
         [0.4409]]])
________________________________
squeezed back tensor([[0.2278, 0.8095, 0.5995],
        [0.0878, 0.0887, 0.1695],
        [0.5426, 0.9110, 0.4409]])


In [70]:
t3, torch.permute(t3, dims = (1,0))

(tensor([[0.2278, 0.8095, 0.5995],
         [0.0878, 0.0887, 0.1695],
         [0.5426, 0.9110, 0.4409]]),
 tensor([[0.2278, 0.0878, 0.5426],
         [0.8095, 0.0887, 0.9110],
         [0.5995, 0.1695, 0.4409]]))

In [72]:
img = torch.rand(size = (224, 224, 3))
img.shape

torch.Size([224, 224, 3])

In [76]:
torch.permute(img, dims = (2, 0, 1)).shape, torch.permute(img, dims = (0, 2, 1)).shape

(torch.Size([3, 224, 224]), torch.Size([224, 3, 224]))

In [83]:
img[0][0][0] = 0.4
print(img[0][0][0])
img[0][0][0] = 0.0
torch.permute(img, dims = (0, 2, 1))[0][0][0]

tensor(0.4000)


tensor(0.)

# Indexing

Same as Numpy

In [84]:
import torch

In [95]:
t = torch.arange(1,100).reshape(11, 3, 3)
t, t.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]],
 
         [[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]],
 
         [[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],
 
         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]],
 
         [[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],
 
         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]],
 
         [[73, 74, 75],
          [76, 77, 78],
          [79, 80, 81]],
 
         [[82, 83, 84],
          [85, 86, 87],
          [88, 89, 90]],
 
         [[91, 92, 93],
          [94, 95, 96],
          [97, 98, 99]]]),
 torch.Size([11, 3, 3]))

In [91]:
t[0] , t[0,1], t[0][1][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(6))

In [97]:
t.shape

torch.Size([11, 3, 3])

In [106]:
t[:, 1, 1]

tensor([ 5, 14, 23, 32, 41, 50, 59, 68, 77, 86, 95])

In [109]:
t, t[6, 1, 2]

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]],
 
         [[28, 29, 30],
          [31, 32, 33],
          [34, 35, 36]],
 
         [[37, 38, 39],
          [40, 41, 42],
          [43, 44, 45]],
 
         [[46, 47, 48],
          [49, 50, 51],
          [52, 53, 54]],
 
         [[55, 56, 57],
          [58, 59, 60],
          [61, 62, 63]],
 
         [[64, 65, 66],
          [67, 68, 69],
          [70, 71, 72]],
 
         [[73, 74, 75],
          [76, 77, 78],
          [79, 80, 81]],
 
         [[82, 83, 84],
          [85, 86, 87],
          [88, 89, 90]],
 
         [[91, 92, 93],
          [94, 95, 96],
          [97, 98, 99]]]),
 tensor(60))

In [114]:
t[:, :, 2].flatten()

tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54,
        57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## NumPy is paramount in using Pytorch, it actually comes with the package

As you can see, the transition between ndarrays and tensors are really seemless

In [119]:
# Numpy array to tensor
import torch
import numpy as np

ndarray = np.arange(1, 8)
tensor = torch.from_numpy(ndarray).type(torch.float32)
# If we do not specify the type after conversion, the torch.from_numpy method is gonna match the type of Numpy

ndarray.dtype, tensor.dtype

(dtype('int64'), torch.float16)

In [121]:
ndarray = ndarray +1
ndarray, tensor
# Memory is not shared

(array([3, 4, 5, 6, 7, 8, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16))

In [128]:
tensor = torch.eye(3, 3)
np_tensor = tensor.numpy()
tensor.dtype, np_tensor.dtype
# Numpy keeps the standard type from pytorch

(torch.float32, dtype('float32'))

# Reproducibility

In [129]:
torch.rand(3, 3)

tensor([[0.2534, 0.5367, 0.4621],
        [0.3159, 0.6779, 0.0820],
        [0.5740, 0.2633, 0.5577]])

In [132]:
torch.manual_seed(0)
torch.rand(3, 3)
# Always the same output

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556]])

This is pretty important apparently

# Using GPU
They are generally faster for computing thanks to CUDE + NVIDIA hardware + Pytorch working to make everything great

### Getting a GPU

1. Easiest method is using google Colab, using their GPU (there are options to upgrade)
2. Using your own, requires setup and you need to buy it.
3. Use cloud computing - GCP, AWS, Azure and etc. Basically allows you to rent computers

For number 2 and 3 it takes a bit of work to setup. Refer back to the Torch documentation for that

### 2. Checking for GPU in Pytorch

In [1]:
import torch
torch.cuda.is_available() # op method

True

In [2]:
# Setup device agnostic code (???)
device = "cuda" if torch.cuda.is_available() else "cpu"

# It is just a check for running on GPU if available and using cpu otherwise

In [3]:
torch.cuda.device_count()

1

##3. Putting tensors(and models) on the GPU

In [4]:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [5]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [6]:
tensor_on_gpu.numpy()
# Will error since Numpy can only do operations with stuff in CPU

TypeError: ignored

In [7]:
np_tensor = tensor_on_gpu.to("cpu").numpy()
np_tensor

array([1, 2, 3])

#Exercises

In [10]:
#2
t2 = torch.rand(7, 7)

In [14]:
#3
t3 = torch.rand(1, 7)
# torch.matmul(t2, t3) will not work since they don't have the same shape
torch.matmul(t2, t3.T)

tensor([[1.8360],
        [0.7810],
        [0.9701],
        [1.7245],
        [1.4408],
        [1.0813],
        [1.1859]])

In [26]:
#4
torch.manual_seed(0)
t2 = torch.rand(7, 7)

torch.manual_seed(0)
t3 = torch.rand(1, 7)
torch.matmul(t2, t3.T)

RuntimeError: ignored

In [25]:
#5

torch.cuda.manual_seed(1234)
torch.rand(2, device = "cuda")

tensor([0.1272, 0.8167], device='cuda:0')

In [ ]:
torch.manual_seed(1)
torch.rand(2, device = "cuda")
# Apparently works as well

In [36]:
#6
torch.manual_seed(1234)
t61 = torch.rand(2, 3)

torch.manual_seed(1234)
t62 = torch.rand(2, 3)

t61.to("cuda")
t62.to("cuda");

In [41]:
#7
t7 = torch.matmul(t61.reshape(3, 2), t62)

In [40]:
torch.matmul(t61, t62.reshape(3, 2))

tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]])

In [50]:
#8
torch.max(t7),torch.min(t7), t7

(tensor(0.5061),
 tensor([[0.1482, 0.0351, 0.2891],
         [0.1420, 0.1258, 0.3244],
         [0.2586, 0.0643, 0.5061]]))

In [52]:
#9
torch.argmax(t7), torch.argmin(t7), t7

(tensor(8),
 tensor(1),
 tensor([[0.1482, 0.0351, 0.2891],
         [0.1420, 0.1258, 0.3244],
         [0.2586, 0.0643, 0.5061]]))

In [55]:
#10
torch.manual_seed(7)
t10 = torch.rand(1, 1, 1, 10)

t10_2 = t10.squeeze()
print(f"Initial tensor with size {t10.shape}: \n {t10}")
print(f"Tensor after squeeze with size {t10_2.shape}: \n {t10_2}")

Initial tensor with size torch.Size([1, 1, 1, 10]): 
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor after squeeze with size torch.Size([10]): 
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
